<?php echo $this->doctype() . PHP_EOL; ?>
<html>
<head>
    <?php
        $this->headLink()->appendStylesheet('/themes/default/css/admin/main.css');
        $this->headLink()->appendStylesheet('/themes/default/css/admin/modal-dialog.css');
        $this->headScript()->appendFile('/themes/default/js/jquery.js');
        $this->headScript()->appendFile('/themes/default/js/ui-buttons.js');
        $this->headScript()->appendFile('/themes/default/js/modal-dialog.js');

        $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
        $this->headMeta()->appendHttpEquiv('Content-Language', 'en-US');

        echo $this->headTitle(' Admin panel ') . PHP_EOL .
            $this->headMeta() . PHP_EOL .
            $this->headLink() . PHP_EOL .
            $this->headScript() . PHP_EOL .
            $this->headStyle() . PHP_EOL;

    ?>
    <script type="text/javascript">
        var clocksInterval = null;
        var container = null;

        var fastVisitDelay = null;

        var fastVisitURL = '<?=$this->url(array('module'=>'members','controller'=>'visit','action'=>'fast','number'=>'PLACEHOLDER'),'default',true);?>';

        var loader = null;

        var fastVisitXHR = false;
        var lastLoaded = null;

        function tickTheClock()
        {
            container.html(new Date().toLocaleTimeString());
        }

        function showSuggestions()
        {
            loader.show();
            var number = $('#fast-visit-field').val();
            if(number.length >= 5) {
                var url = fastVisitURL.replace('PLACEHOLDER', number);

                if(number == lastLoaded)
                    return;
                lastLoaded = number;
                if(fastVisitXHR) {
                    fastVisitXHR.abort();
                }

                fastVisitXHR  = $.ajax({
                    url: url,
                    success: function(data) {
                        $('#visit-target').html(data);
                        fastVisitXHR = false;
                        loader.hide();
                    }
                });

            }
        }

        $(document).ready(function(){
            container = $('#hours');
            clocksInterval = setInterval(tickTheClock,1000)
            tickTheClock();


            loader = $('#visit-loader');
            $('#fast-visit-field').keyup(function(e){
                clearTimeout(fastVisitDelay);
                fastVisitDelay = setTimeout(showSuggestions, 400);
            });
        });

    </script>
</head>
<body>
<div id="main-content">
    <div id="navbar-container">
        <img src="/themes/default/images/logo.jpg" width="200" />

        <?php
        echo $this->navigation()->menu();
        ?>

        <div id="fast-visit">
            <input name="id" autocomplete="off" type="text" id="fast-visit-field" />
            <div id="visit-loader"><img src="/themes/default/images/ajax-loader.gif" alt="loading..."></div>
            <div id="visit-target"></div>
        </div>

        <div id="in_club">

            <?php
                $listDQL = Members_Model_DbTable_Member::getInstance()->getList();
                $listDQL->innerJoin('m.Visits v WITH v.day = DATE(NOW()) AND exit_time IS NULL');
                $list = $listDQL->execute();
            ?>

            <?=$this->link($this->translate('in_club_members').': '.$list->count(), $this->url(array('module'=>'members','action'=>'list', 'saved-filter'=>'inside'), 'admin', true));?>

        </div>
        <div id="clocks">
            <span id="hours"></span><br />
            <?=date('d.m.Y');?>
        </div>

    </div>
    <div id="mainview">
        <?php echo $this->flashMessenger(); ?>

        <?php echo $this->layout()->top; ?>
        <div id="mainview-content"><?php echo $this->layout()->content;?></div>

    </div>
</div>

</body>
</html>
