<?php echo $this->doctype() . PHP_EOL; ?>
<html>
<head>
    <?php
    $this->headMeta()->appendHttpEquiv('Content-Language', 'en-US');
    $this->headLink()->appendStylesheet('/themes/default/css/main.css?v2');
    $this->headScript()->appendFile('/themes/default/js/jquery.js');
    $this->headScript()->appendFile('/themes/default/js/ui-buttons.js');



        echo $this->headTitle('Login', Zend_View_Helper_Placeholder_Container_Abstract::PREPEND)->setSeparator(' : ').PHP_EOL;
        echo $this->headMeta().PHP_EOL;
        echo $this->headLink().PHP_EOL;
        echo $this->headStyle().PHP_EOL;

        echo $this->headScript().PHP_EOL;
    ?>

</head>
<body>
<div style="width: 350px;
    margin: 20px auto; ">
    <div style="text-align: center;">
    <img src="/themes/default/images/logo.jpg" width="200" />
    </div>

    <?php echo $this->flashMessenger(); ?>
    <br />
    <?php echo $this->layout()->content; ?>
</div>

</body>
</html>
