<ul class="<?php echo $this->navigation()->menu()->getUlClass(); ?>">
<?php
/** @var Zend_Navigation_Page_Mvc $page  */
foreach($this->container as $page) {

    $action = $page->getAction();
    if(empty($action)) {
        $action = 'index';
    }

    if(!$this->allowed($page->getModule().'.'.$page->getController().'.'.$action)) {
        continue;
    }

    $cssClass = $page->isActive() === true ? ' class="active"' : '';
    echo '<li' . $cssClass . '><a href="'. $page->getHref() .'"><span>' . $page->label . '</span></a></li>';

//    if ($page->hasPages()) {
//        echo $this->partial('menuPartial.phtml', array('container' => $page->getPages()));
//    }

}
?>
</ul>