<div class="brdBottom cc">
        <h1 class="titleLogin">Регистрация</h1>
        <a href="/help/login" class="helpIcon"><img src="/themes/interteam/images/big_help.gif"></a>
</div>

<?php $this->jquery()->addOnload('hideJuridicFields($("#'.$this->regForm->getElement('role_id')->getId().'").val());'); ?>

<?php $this->headScript()->captureStart(); ?>

function hideJuridicFields(value)
{
    if(value == 7) {
     $('#ownership-label').show();
        $('#ownership-element').show();

        $('#company-label').show();
        $('#company-element').show();

        $('#web-label').show();
        $('#web-element').show();
    } else {

        $('#ownership-label').hide();
        $('#ownership-element').hide();

        $('#company-label').hide();
        $('#company-element').hide();

        $('#web-label').hide();
        $('#web-element').hide();
    }
}

<?php $this->headScript()->captureEnd(); ?>
<?php
    $this->regForm->getElement('role_id')->setAttrib('onchange','hideJuridicFields(this.value);');
?>

<?php 
    $this->regForm->getElement('region')->setAttrib('onchange','loadCities(this)')->setAttrib('class','regions-selector');
?>

<?php $this->headScript()->captureStart(); ?>

function loadCities(regionObject)
{
   var regions = new Array();
   
   regions.push($(regionObject).val());  
   

   $.getJSON('<?php echo $this->url(array('action'=>'get-cities','controller'=>'ajax', 'module'=>'region'), 'default', true);?>', 
    {regions:regions}, 
    function(data){ 

        var cityElement = $('#city');
        var html = '';
        $(data.cities).each(function(i, city) {
            html += '<option  value="'+city.id+'">'+city.title+'</option>';
        });

        cityElement.html(html);

    });

}

<?php $this->headScript()->captureEnd(); ?>

<?php echo $this->regForm; ?>