<div>
    <h2 class="addr">
        <?php echo $this->userIdentity->firstname ;?> <?php echo $this->userIdentity->lastname ;?>
        <span class="w_norm">2345068382947</span> <img src="/themes/interteam/images/help.png" />
    </h2>
    <?php if(!empty($this->manager)) {?>
    <div class="info">
            <p><strong>Ваш менеджер:</strong></p>
            <p><?php echo $this->manager->firstname;?> <?php echo $this->manager->lastname;?> <a href="mailto:<?php echo $this->manager->email;?>" class="mail">
                    <img src="/themes/interteam/images/mail.gif" width="13" height="8" alt="mail"></a>
            </p>
            <p>+38(<?php echo $this->manager->mobile_operator;?>) <?php echo $this->manager->mobile_number;?></p>
    </div>
    <?php }?>
</div>