Sysmap_Model_Mapper_Sysmap:
  Sysmap_Model_Mapper_Sysmap_1:
    mca: "*.*.*"
    hash: "0-816563134a61e1b2c7cd7899b126bde4"
    title: "All"
    lft: 1
    rgt: 4
    level: 0
  Sysmap_Model_Mapper_Sysmap_2:
    mca: "*.admin.*"
    hash: "1-9fe21b10c624fe854dc4aa3387a0e1ec"
    title: "All admin actions"
    lft: 2
    rgt: 3
    level: 1