<table class="admin-table-list">
    <tr>
        <th width="20">ID</th>
        <th>Title</th>
        <th width="150">System name</th>
        <th width="200">Theme name</th>
        <th width="20">Published</th>
        <th width="10">Actions</th>
    </tr>
    <?php foreach ($this->pager->execute() as $item) {
 ?>
        <tr>
            <td align="center"><?php echo $item->id; ?></td>
            <td>
                <?php echo $this->link($item->title, $this->url(array('action' => 'edit-layout', 'id' => $item->id))); ?>
            </td>
            <td align="center"><?php echo $item->name; ?></td>
            <td align="center"><?php echo $item->Theme->title; ?></td>
            <td align="center"><a href="<?php echo $this->url(array('action' => 'publish-layout',  'id' => $item->id)); ?>" class="icon16 <?php
            if ($item->published)
                echo 'icon-published'; else
                echo 'icon-not-published'
    ?>"></a></td>
        <td align="center" nowrap="nowrap">
            <?php echo $this->link('Widgets', $this->url(array('action' => 'widgets', 'layid' => $item->id)),
                            array('class' => 'icon-layout_content')); ?>
            <?php echo $this->link('Edit', $this->url(array('action' => 'edit-layout', 'id' => $item->id)),
                            array('class' => 'edit-item')); ?>
            <?php echo $this->link('Delete', $this->url(array('action' => 'delete-layout', 'id' => $item->id)),
                    array('class' => 'delete-item'), 'Delete this layout?'); ?>
        </td>
    </tr>
<?php } ?>
</table>