<table class="admin-table-list">
    <tr>
        <th width="20">ID</th>
        <th>Title</th>
        <th width="150">System name</th>
        <th width="10">Current</th>
        <th width="10">Actions</th>
    </tr>
    <?php foreach ($this->pager->execute() as $item) {
 ?>
        <tr>
            <td align="center"><?php echo $item->id; ?></td>
            <td ><?php echo $this->link($item->title, $this->url(array('action' => 'edit-theme', 'id' => $item->id))); ?></td>
            <td align="center"><?php echo $item->name; ?></td>
            <td align="center"><a href="<?php echo $this->url(array('action' => 'current-theme', 'id' => $item->id)); ?>" class="icon16 <?php if ($item->current)
            echo 'icon-published'; else
            echo 'icon-not-published' ?>"></a></td>
            <td align="center" nowrap="nowrap">
                <?php echo $this->link('Layouts', $this->url(array('action' => 'layouts', 'tpl' => $item->id)),
                        array('class' => 'icon-xhtml')); ?>
                <?php echo $this->link('Edit', $this->url(array('action' => 'edit-theme', 'id' => $item->id)),
                        array('class' => 'edit-item')); ?>
                <?php echo $this->link('Delete', $this->url(array('action' => 'delete-theme', 'id' => $item->id)),
                        array('class' => 'delete-item'), 'Delete this theme?'); ?>
        </td>
    </tr>
<?php } ?>
</table>
