actAs: [Timestampable]

Products_Model_Mapper_Product:
  connection: doctrine
  tableName: products_product
  columns:
    id:
      type: integer(11)
      unsigned: true
      primary: true
      autoincrement: true
    title:
      type: string(255)
      unique: true
    price:
      type: decimal(10)
      scale: 2
      notnull: true
    amount:
      type: integer(11)
      unsigned: true
      notnull: true
    active:
      type: boolean
      default: true

Products_Model_Mapper_Sale:
  connection: doctrine
  tableName: products_sales
  columns:
    id:
      type: integer(11)
      unsigned: true
      primary: true
      autoincrement: true
    product_id:
      type: integer(11)
      unsigned: true
      notnull: true
    user_id:
      type: integer(11)
  relations:
    Product:
      class: Products_Model_Mapper_Product
      local: product_id
      foreign: id
      foreignAlias: Sales
      onDelete: CASCADE
    User:
      class: User_Model_Mapper_User
      local: user_id
      foreign: id
      foreignAlias: Sales
      onDelete: SET NULL