<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Members_Model_Mapper_BaseVisit', 'doctrine');

/**
 * Members_Model_Mapper_BaseVisit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property date $day
 * @property time $enter_time
 * @property time $exit_time
 * @property integer $subscription_id
 * @property integer $user_id
 * @property Members_Model_Mapper_Member $Member
 * @property Members_Model_Mapper_Subscription $Subscription
 * @property User_Model_Mapper_User $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Members_Model_Mapper_BaseVisit extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('members_visits');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('member_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('day', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('enter_time', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('exit_time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('subscription_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Members_Model_Mapper_Member as Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Members_Model_Mapper_Subscription as Subscription', array(
             'local' => 'subscription_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('User_Model_Mapper_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}