<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Members_Model_Mapper_BaseSubscriptionType', 'doctrine');

/**
 * Members_Model_Mapper_BaseSubscriptionType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property integer $duration
 * @property enum $units
 * @property time $enter_time
 * @property time $exit_time
 * @property integer $visits_per_week
 * @property integer $price
 * @property Doctrine_Collection $Subscriptions
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Members_Model_Mapper_BaseSubscriptionType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('members_subscription_types');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('duration', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('units', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'HOURS',
              1 => 'DAYS',
              2 => 'WEEKS',
              3 => 'MONTHS',
              4 => 'YEARS',
             ),
             ));
        $this->hasColumn('enter_time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('exit_time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('visits_per_week', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('price', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Members_Model_Mapper_Subscription as Subscriptions', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}