<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Members_Model_Mapper_BaseMember', 'doctrine');

/**
 * Members_Model_Mapper_BaseMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $number
 * @property string $email
 * @property enum $sex
 * @property string $firstname
 * @property string $lastname
 * @property date $birth_date
 * @property string $phone
 * @property integer $user_id
 * @property User_Model_Mapper_User $User
 * @property Doctrine_Collection $Subscriptions
 * @property Doctrine_Collection $Visits
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Members_Model_Mapper_BaseMember extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('members_members');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('number', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'unique' => true,
             'length' => '11',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('sex', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'MALE',
              1 => 'FEMALE',
             ),
             'default' => 'MALE',
             ));
        $this->hasColumn('firstname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('lastname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('birth_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('phone', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_Mapper_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('Members_Model_Mapper_Subscription as Subscriptions', array(
             'local' => 'id',
             'foreign' => 'member_id'));

        $this->hasMany('Members_Model_Mapper_Visit as Visits', array(
             'local' => 'id',
             'foreign' => 'member_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}