<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Members_Model_Mapper_BaseSubscription', 'doctrine');

/**
 * Members_Model_Mapper_BaseSubscription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property decimal $price_on_signup
 * @property integer $type_id
 * @property enum $status
 * @property date $start_date
 * @property date $expire_date
 * @property Members_Model_Mapper_Member $Member
 * @property Members_Model_Mapper_BaseSubscriptionType $Type
 * @property Doctrine_Collection $Visits
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Members_Model_Mapper_BaseSubscription extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('members_subscriptions');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('member_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('price_on_signup', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('type_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'PENDING',
              1 => 'ACTIVE',
              2 => 'EXPIRED',
              3 => 'CANCELED',
             ),
             'default' => 'PENDING',
             ));
        $this->hasColumn('start_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('expire_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Members_Model_Mapper_Member as Member', array(
             'local' => 'member_id',
             'foreign' => 'id'));

        $this->hasOne('Members_Model_Mapper_BaseSubscriptionType as Type', array(
             'local' => 'type_id',
             'foreign' => 'id'));

        $this->hasMany('Members_Model_Mapper_Visit as Visits', array(
             'local' => 'id',
             'foreign' => 'subscription_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}