<h1><?php echo $this->translate('visits_list');?></h1>

<h2>Today</h2>
<table class="admin-table-list">
    <?php
    /** @var $visit Members_Model_Mapper_Visit */
    foreach($this->todayList as $visit):

        ?>
    <tr class="row" onclick="window.location.href = '<?php echo $this->url(array('action'=>'view','id'=>$visit->id));?>' ">
        <td width="200"><?php echo $visit->Member->getFullName();?> - <?php echo $visit->Member->number;?></td>
        <td width="60"><?php echo $visit->enter_time;?></td>
        <td><?php echo $visit->exit_time;?></td>
    </tr>
    <?php endforeach;?>
</table>
<?php
$last = strtotime("-1 day");

$yesterday = Members_Model_DbTable_Visit::getInstance()->getDayVisitsList(date("Y-m-d", strtotime("-1 day")));

$count = $yesterday->count();

echo '<h2>Yesterday ('. $count . ')</h2>';
echo '<h2>This Month ('. $count . ')</h2>';
echo '<h2>Previous Month ('. $count . ')</h2>';
echo '<h2>This Year ('. $count . ')</h2>';
echo '<h2>Previous Year ('. $count . ')</h2>';
