<?php
/** @var $visit Members_Model_Mapper_Visit */
$visit = $this->mapper;
?>
<h1><?php echo $this->translate("visit_info");?></h1>
<table class="admin-table-info">
    <tr>
        <th><?php echo $this->translate('visit_day');?></th>
        <td><?php echo $visit->day;?></td>
    </tr>
    <tr>
        <th><?php echo $this->translate('enter_time');?></th>
        <td><?php echo $visit->enter_time;?></td>
    </tr>
    <tr>
        <th><?php echo $this->translate('exit_time');?></th>
        <td><?php echo empty($visit->exit_time) ? $this->translate('in_club') : $visit->exit_time;?></td>
    </tr>
    <tr>
        <th><?php echo $this->translate('member');?></th>
        <td><?php echo $visit->Member->getFullNameAndNumber();?></td>
    </tr>
</table>
