actAs: [Timestampable]

Members_Model_Mapper_Member:
  connection: doctrine
  tableName: members_members
  columns:
    id:
      type: integer(11)
      unsigned: true
      primary: true
      autoincrement: true
    number:
      type: integer(11)
      unsigned: true
      notnull: true
      unique: true
    email:
      type: string(255)
      unique: true
    sex:
      type: enum
      values:
        - MALE
        - FEMALE
      default: MALE
    firstname:
      type: string(255)
      notnull: true
    lastname:
      type: string(255)
      notnull: true
    birth_date:
      type: date
      notnull: true
    phone:
      type: string(64)

Members_Model_Mapper_Subscription:
  connection: doctrine
  tableName: members_subscriptions
  columns:
    id:
      type: integer(11)
      unsigned: true
      primary: true
      autoincrement: true
    member_id:
      type: integer(11)
      unsigned: true
      notnull: true
    price_on_signup:
      type: decimal(10)
      scale: 2
      notnull: true
    type_id:
      type: integer(11)
      unsigned: true
      notnull: true
    status:
      type: enum
      values:
        - PENDING
        - ACTIVE
        - EXPIRED
        - CANCELED
      default: PENDING
    start_date:
      type: date
      notnull: true
    expire_date:
      type: date
      notnull: true
  relations:
    Member:
      class: Members_Model_Mapper_Member
      local: member_id
      foreign: id
      foreignAlias: Subscriptions
    Type:
      class: Members_Model_Mapper_SubscriptionType
      local: type_id
      foreign: id
      foreignAlias: Subscriptions

Members_Model_Mapper_Visit:
  connection: doctrine
  tableName: members_visits
  columns:
    id:
      type: integer(11)
      unsigned: true
      primary: true
      autoincrement: true
    member_id:
      type: integer(11)
      unsigned: true
      notnull: true
    day:
      type: date
      notnull: true
    enter_time:
      type: time
      notnull: true
    exit_time:
      type: time
      default: null
    subscription_id:
      type: integer(11)
      unsigned: true
      notnull: true
  relations:
    Member:
      class: Members_Model_Mapper_Member
      local: member_id
      foreign: id
      foreignAlias: Visits
    Subscription:
      class: Members_Model_Mapper_Subscription
      local: subscription_id
      foreign: id
      foreignAlias: Visits


Members_Model_Mapper_SubscriptionType:
  connection: doctrine
  tableName: members_subscription_types
  columns:
    id:
      type: integer(11)
      unsigned: true
      primary: true
      autoincrement: true
    title:
      type: string(255)
      notnull: true
    description:
      type: string(255)
      notnull: true
    duration:
      type: integer(4)
      notnull: true
    units:
      type: enum
      values:
        - HOURS
        - DAYS
        - WEEKS
        - MONTHS
        - YEARS
    enter_time:
      type: time
    exit_time:
      type: time
    visits_per_week:
      type: integer(4)
    price:
      type: decimal(10)
      scale: 2