<?php
/**
 * Description
 *
 * @author Serghei Ilin <criolit@gmail.com>
 * @version $Id$
 */
$menu = $this->navigation()->menu();

$menu->setOnlyActiveBranch(false)
     ->setRenderParents(false)
     ->setMinDepth(1)
     ->setMaxDepth(null);

if (empty($this->css) === false)
    $menu->setUlClass($this->css);

if (empty($this->partial))
    echo $menu->renderMenu($this->nav);
else
    echo $menu->renderPartial($this->nav, $this->partial . '.phtml');