<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('User_Model_Mapper_BaseRule', 'doctrine');

/**
 * User_Model_Mapper_BaseRule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $role_id
 * @property string $resource_id
 * @property enum $rule
 * @property User_Model_Mapper_Role $Role
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_Mapper_BaseRule extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user_rules');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('role_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('resource_id', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('rule', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'allow',
              1 => 'deny',
             ),
             'default' => 'allow',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_Mapper_Role as Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));
    }
}