<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Templater_Model_Mapper_BaseLayoutPoint', 'doctrine');

/**
 * Templater_Model_Mapper_BaseLayoutPoint
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $map_id
 * @property integer $layout_id
 * @property Templater_Model_Mapper_Layout $Layout
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Templater_Model_Mapper_BaseLayoutPoint extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('templater_layout_points');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('map_id', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             ));
        $this->hasColumn('layout_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Templater_Model_Mapper_Layout as Layout', array(
             'local' => 'layout_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}