<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Templater_Model_Mapper_BaseWidgetPoint', 'doctrine');

/**
 * Templater_Model_Mapper_BaseWidgetPoint
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $map_id
 * @property integer $widget_id
 * @property Templater_Model_Mapper_Widget $Widget
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Templater_Model_Mapper_BaseWidgetPoint extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('templater_widget_points');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('map_id', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             ));
        $this->hasColumn('widget_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Templater_Model_Mapper_Widget as Widget', array(
             'local' => 'widget_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}