<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Templater_Model_Mapper_BaseLayout', 'doctrine');

/**
 * Templater_Model_Mapper_BaseLayout
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $name
 * @property integer $theme_id
 * @property array $params
 * @property boolean $published
 * @property Templater_Model_Mapper_Theme $Theme
 * @property Doctrine_Collection $Widgets
 * @property Doctrine_Collection $Points
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Templater_Model_Mapper_BaseLayout extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('templater_layouts');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('theme_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('params', 'array', null, array(
             'type' => 'array',
             ));
        $this->hasColumn('published', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Templater_Model_Mapper_Theme as Theme', array(
             'local' => 'theme_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Templater_Model_Mapper_Widget as Widgets', array(
             'local' => 'id',
             'foreign' => 'layout_id'));

        $this->hasMany('Templater_Model_Mapper_BaseLayoutPoint as Points', array(
             'local' => 'id',
             'foreign' => 'layout_id',
             'onDelete' => 'CASCADE'));
    }
}