<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Templater_Model_Mapper_BaseTheme', 'doctrine');

/**
 * Templater_Model_Mapper_BaseTheme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $name
 * @property boolean $current
 * @property integer $ordering
 * @property Doctrine_Collection $Layouts
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Templater_Model_Mapper_BaseTheme extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('templater_themes');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('current', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('ordering', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Templater_Model_Mapper_Layout as Layouts', array(
             'local' => 'id',
             'foreign' => 'theme_id',
             'onDelete' => 'CASCADE'));
    }
}