User_Model_Mapper_User:
  connection: doctrine
  tableName: user_users
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    login:
      type: string(255)
    password:
      type: string(32)
    role_id:
      type: integer(11)
    active:
      type: boolean
    firstname:
      type: string(255)
    lastname:
      type: string(255)
    birth:
      type: string(255)
    email:
      type: string(255)
    phone:
      type: string(255)
    zip:
      type: string(255)
    token:
      type: string(255)
    token_date:
      type: datetime
  relations:
    Role:
      class: User_Model_Mapper_Role
      local: role_id
      foreign: id
      type: one

User_Model_Mapper_Role:
  connection: doctrine
  tableName: user_roles
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name:
      type: string(255)
    parent_id:
      type: integer(11)
    is_default:
      type: boolean
    register:
      type: boolean
  relations:
    Rules:
      class: User_Model_Mapper_Rule
      local: id
      foreign: role_id
      type: many

User_Model_Mapper_Rule:
  connection: doctrine
  tableName: user_rules
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    role_id:
      type: integer(11)
    resource_id:
      type: string(50)
    rule:
      type: enum
      values:
        - allow
        - deny
      default: allow
  relations:
    Role:
      class: User_Model_Mapper_Role
      local: role_id
      foreign: id
      type: one