User_Model_Mapper_User:
  connection: doctrine
  tableName: user_users
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    login:
      type: string(255)
    password:
      type: string(40)
    role:
      type: enum
      values:
        - MANAGER
        - ADMIN
      default: MANAGER
    firstname:
      type: string(255)
    lastname:
      type: string(255)
    birth:
      type: string(255)
    email:
      type: string(255)
    phone:
      type: string(255)
    zip:
      type: string(255)
    token:
      type: string(255)
    token_date:
      type: datetime