<ul class="<?php echo $this->navigation()->menu()->getUlClass(); ?>">
<?php
foreach($this->container as $page) {
    $cssClass = $page->isActive() === true ? ' class="active"' : '';
    echo '<li' . $cssClass . '><a href="'. $page->getHref() .'"><span>' . $page->label . '</span></a>';

    if ($page->hasPages()) {
        echo $this->partial('menuPartial.phtml', array('container' => $page->getPages()));
    }
}
?>
</ul>