<?php
/** @var $member Members_Model_Mapper_Member */
$member = $this->member;

$activeSubscription = $member->getActiveSubscription();
?>
<table class="admin-table-list">
    <tr class="title">
        <th><?php echo $this->translate('subscription');?></th>
        <th><?php echo $this->translate('price');?></th>
    </tr>
<?php
/** @var $type Members_Model_Mapper_SubscriptionType */
foreach($this->types as $type):
?>
<tr>
    <td><?php echo $this->link($type->title , $this->url(array('type'=>$type->id)));?></td>
    <td align="right"><?php echo $this->link($type->price, $this->url(array('type'=>$type->id)));?></td>
</tr>
<?php endforeach;?>
</table>
<p class="description">
<?php echo $this->translate('Select subscription you want to add');?>
</p>