<h1><?php echo $this->translate('members_list');?></h1>
<form action="<?php echo $this->url();?>" method="get" id="list-filter">
<table class="table-filter">
    <tr>
        <td width="100"><input type="text" name="number" id="filter_number" placeholder="Number" autocomplete="off" value="<?php echo $this->number;?>" style="width: 80px;" size="6" /></td>
        <td width="210"><input type="text" name="name" id="filter_name" placeholder="Name" autocomplete="off" value="<?php echo $this->name;?>" /></td>
        <td>
            <input type="submit" class="button" value="filter" />
            <input type="reset" class="button light-grey-button" id="reset-filter" value="reset" />
        <?php
            echo $this->link('create_new_member', $this->url(array('module'=>'members','action'=>'add'),'admin',true), array('class'=>'button plus-icon'));?></td>
    </tr>
</table>
</form>
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td valign="top">
            <table class="admin-table-list" id="members-list">
                <?php echo $this->partial('/ajax/members-list.phtml', array('list' => $this->list, 'moreResultsExists' => $this->moreResultsExists));?>
            </table>
            <?php echo $this->link('more_results', $this->url(array('page'=>$this->page)), array('class'=>'button light-grey-button', 'id'=>'load-more-results'));?>
        </td>
        <td width="200" valign="top">
            <div class="members-list-filters">
                <ul>
                    <li<?php if($this->savedFilter =='all') echo ' class="active"';?>><?php echo $this->link('All members', $this->url(array('module'=>'members','action'=>'list', 'saved-filter'=>'all'), 'admin', true));?></li>
                    <li<?php if($this->savedFilter =='inside') echo ' class="active"';?>><?php echo $this->link('in_club_members', $this->url(array('module'=>'members','action'=>'list', 'saved-filter'=>'inside'), 'admin', true));?></li>
                    <li<?php if($this->savedFilter =='active') echo ' class="active"';?>><?php echo $this->link('Active members', $this->url(array('module'=>'members','action'=>'list', 'saved-filter'=>'active'), 'admin', true));?></li>
                    <li<?php if($this->savedFilter =='todays') echo ' class="active"';?>><?php echo $this->link('Today\'s members', $this->url(array('module'=>'members','action'=>'list', 'saved-filter'=>'todays'), 'admin', true));?></li>
                    <li<?php if($this->savedFilter =='expired') echo ' class="active"';?>><?php echo $this->link('Expired members', $this->url(array('module'=>'members','action'=>'list', 'saved-filter'=>'expired'), 'admin', true));?></li>
                    <li<?php if($this->savedFilter =='expire-in-1-week') echo ' class="active"';?>><?php echo $this->link('Expire in 1 week', $this->url(array('module'=>'members','action'=>'list', 'saved-filter'=>'expire-in-1-week'), 'admin', true));?></li>
                    <li><?php echo $this->link('Emails list', $this->url(array('module'=>'members','controller'=>'report','action'=>'emails-list'), 'default', true));?></li>
                    <li><?php echo $this->link('Weekly visits report', $this->url(array('module'=>'members','controller'=>'report','action'=>'week-visits-report'), 'default', true));?></li>
                </ul>
            </div>
        </td>
    </tr>
</table>


<script type="text/javascript">
var moreResultsExists = <?php echo $this->moreResultsExists? 'true' : 'false';?>;

var nextPageNumber = '<?php echo $this->page+1;?>';

var filterURL = '<?php echo $this->url(array('module'=>'members', 'action'=>'list', 'page' => 1, 'saved-filter'=>$this->savedFilter), 'admin', true);?>';

var filterFieldTimeout = setTimeout(function(){}, 100);

var paramsString = '/';

var showResetButton = <?php echo empty($this->number) && empty($this->name) ? 'false' : 'true';?>;
<?php

if(!empty($this->number)) echo 'paramsString += "number/'.$this->number.'/"';
if(!empty($this->name)) echo 'paramsString += "name/'.$this->name.'/"';
?>

var originalMoreResultsHref = '';

$(function(){
    $('#list-filter').submit(function(event){
        event.preventDefault();

        var formData = $(this).serializeArray();

        paramsString = '/';
        $.each(formData, function(i, o){

            if(o.value != '')
                paramsString += o.name + '/' + o.value;

        });

        $(this).attr('action', filterURL + paramsString);


        $.get($(this).attr('action'), function(data){
            $('#members-list tbody').html(data);
            if(moreResultsExists == false) {
                $('#load-more-results').hide();
            } else {
                $('#load-more-results').show();
            }

            if(paramsString != '/')
                $('#reset-filter').next().show();
            else
                $('#reset-filter').next().hide();

            nextPageNumber = 2;
        });
    });


    function inputChanged(event) {
        clearTimeout(filterFieldTimeout);
        filterFieldTimeout = setTimeout(function(){
            $('#list-filter').submit();
        }, 400);
    }

    $('#list-filter input').bind({change: inputChanged, keyup: inputChanged});

    $('#reset-filter').click(function(event){
        $('#list-filter input').val('');
        $('#list-filter').submit();
    });

    $('#load-more-results').click(function(event){
        event.preventDefault();

        var url = (filterURL+paramsString).replace(/page\/\d/i, 'page/'+nextPageNumber);

        $.get(url, function(data){
            nextPageNumber++;
            $('#members-list tbody').append(data);
            if(moreResultsExists == false) {
                $('#load-more-results').hide();
            } else {
                $('#load-more-results').show();
            }
        });
    });

    if(moreResultsExists == false)
        $('#load-more-results').hide();

    if(showResetButton == false) {
        $('#reset-filter').next().hide();
    }
});
</script>