<h1><?php echo $this->translate('subscriptions_list');?></h1>

<?php echo $this->link('create_new_type', $this->url(array('module'=>'members','controller'=>'subscription','action'=>'edit'),'default',true), array('class'=>'button plus-icon'));?>
<table class="admin-table-list" id="subscriptions-list">
    <?php
    /** @var $subscription Members_Model_Mapper_SubscriptionType */
    foreach($this->list  as $subscription):?>
    <tr class="row" onclick="window.location.href = '<?php echo $this->url(array('module'=>'members','controller'=>'subscription','action'=>'edit','id'=>$subscription->id), 'default', true);?>' ">
        <td><?php echo $subscription->title;?></td>
    </tr>
    <?php endforeach;?>
</table>

