<?php
$editAction = 'edit-menu-item';

if ($this->arrayTreeItem['level'] == 0)
	$editAction = 'edit-menu';
?>
<tr>
	<td>
		<?php
		$title  = '';
		$title .= str_repeat('&nbsp;&nbsp;', $this->arrayTreeItem['level']);

		if($this->arrayTreeItem['level'] > 0)
			$title .= '<sup>|</sup>-&nbsp;';

		echo $title . $this->arrayTreeItem['title'];
		?>
	</td>
    <td>
        <?php
        if (!empty($this->arrayTreeItem['route']))
            echo $this->arrayTreeItem['route'];
        ?>
    </td>
	<td align="center" nowrap="nowrap">
		<?php
		if ($this->arrayTreeItem['read_only'] == false):
			echo $this->link(
				'edit',
				$this->url(array('action' => $editAction, 'module' => 'navigation', 'id' => $this->arrayTreeItem['id'])),
				array('class' => 'edit-item')
			);
		?>

		&nbsp;

		<?php
			echo $this->link(
				'delete',
				$this->url(array('action' => 'delete-menu-item', 'module' => 'navigation', 'id' => $this->arrayTreeItem['id'])),
				array('class' => 'delete-item')
			);

		endif;
		?>
	</td>
</tr>