<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Products_Model_Mapper_BaseProduct', 'doctrine');

/**
 * Products_Model_Mapper_BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property decimal $price
 * @property Doctrine_Collection $Sales
 * @property Doctrine_Collection $Stock
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Products_Model_Mapper_BaseProduct extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('products_product');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('price', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => '10',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Products_Model_Mapper_Sale as Sales', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('Products_Model_Mapper_Stock as Stock', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}