<?php
$this->headScript()->appendFile('https://www.google.com/jsapi');

$types = Members_Model_DbTable_SubscriptionType::getInstance()->findAll();

?>

<table width="100%">
    <tr>
        <td valign="top" width="200">

        </td>
        <td>

            <script type="text/javascript">
                <?php //$this->headScript()->captureStart();?>
                // Load the Visualization API and the piechart package.
                google.load('visualization', '1.0', {'packages':['corechart']});

                // Set a callback to run when the Google Visualization API is loaded.
                google.setOnLoadCallback(drawChart);

                // Callback that creates and populates a data table,
                // instantiates the pie chart, passes in the data and
                // draws it.
                function drawChart() {

                    // Create the data table.
                    var data = new google.visualization.DataTable();
                    data.addColumn('string', 'Title');
                    data.addColumn('number', 'Visits');

                    data.addRows([
                    <?php /** @var $type Members_Model_Mapper_SubscriptionType */
                    foreach($types as $type):?>
                        ['<?php echo $type->title;?>', <?php echo $type->countSubscriptions();?>],

                        <?php endforeach;?>
                    ]);

// Set chart options
                    var options = {'title':'<?php echo $this->translate('subscriptions_chart');?>','width':640,'height':480};

// Instantiate and draw our chart, passing in some options.
                    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
                    chart.draw(data, options);
                }
                <?php //$this->headScript()->captureEnd();?>
            </script>

            <div id="chart_div"></div>
        </td>
    </tr>
</table>


