<table class="admin-table-list">
<?php
/** @var $subscription Members_Model_Mapper_Subscription */
foreach($this->list as $subscription):
    $member = $subscription->Member;
    $activeSubscription = $member->getActiveSubscription();
    $lastVisit = $member->getLastVisit();
    ?>
    <tr class="row" onclick="window.location.href = '<?php echo $this->url(array('module'=>'members','action'=>'view','id'=>$member->id), 'admin', true);?>' ">
        <td width="100"><?php echo $member->number;?></td>
        <td width="200"><?php echo $member->getFullName();?></td>
    </tr>
<?php endforeach;?>
</table>

