<style type="text/css">
    .week-visits-report th {

        height: 20px;

    }

    .week-visits-report tbody th {
        height: 30px;
    }

    .week-visits-report tbody tr th, .week-visits-report tbody tr td {
        border-bottom: 1px solid silver;
        border-left: 1px solid silver;
        border-right: 1px solid silver;
        padding: 5px;

    }

    .week-visits-report {
        border-collapse: collapse;
        border-top: 1px solid silver;
    }
</style>
<?php

//$firstVisitInSystem = Members_Model_DbTable_Visit::getInstance()->getFirstVisitEver();
$day = strtotime('2011-10-15');

$startWeeksList = new Zend_Date();
$startWeeksList->setYear(date('Y', $day));
$startWeeksList->setWeek(date('W', $day));
$startWeeksList->setWeekday(1);
$startWeeksList->set('01:00:00', Zend_Date::TIMES);

$today = new Zend_Date();

$year = $startWeeksList->toString('Y');
$month = $startWeeksList->toString('M');
?>
<form action="<?=$this->url()?>">
    <label for="week">Week:</label>
    <select name="week" id="week">
        <?php
        while($startWeeksList <= $today) {

            $listWeek = $startWeeksList->toString('Y').'-'.$startWeeksList->toString('w');

            if($listWeek == $this->week) {
                $selected = 'selected';
            } else {
                $selected = '';
            }
            echo '<option value="'.$listWeek.'" '.$selected.'>'.$startWeeksList->toString('Y-M-d').'</option>';
            $startWeeksList->addWeek(1);
        }
        ?>

    </select>

    <input type="submit" value="Show" />
</form>

<h2>Report</h2>
<?
$totals = array();
$totalDays = array(0,0,0,0,0,0,0,0);
$totalAllDays = 0;
?>
<table class="week-visits-report" cellpadding="0" cellspacing="0">
    <tr>
        <th width="50">Hour</th>
        <th width="130">Mon</th>
        <th width="130">Tue</th>
        <th width="130">Wed</th>
        <th width="130">Thu</th>
        <th width="130">Fri</th>
        <th width="130">Sat</th>
        <th width="130">Sun</th>
        <th width="130" colspan="2">Total by hour</th>
    </tr>
    <tbody>
<?php foreach($this->visits as $hour => $days):
    $totals[$hour] = array();

    ?>
    <tr>
        <th valign="top"><?=$hour?>:00</th>

        <?php for($i=1;$i<=7;$i++):?>
        <td valign="top">
            <?php
            if(!empty($days[$i])) {
                $day = $days[$i];

                $totalDays[$i] += count($day);
                foreach($day as $visit):
                    $totals[$hour][$visit->member_id][] = $visit;

                    ?>
                   <div class="member">
                       <span class="member-number"><?=$visit->Member->number?></span>
                       <span class="member-name"><?=$visit->Member->getFullName()?></span>
                   </div>
                <? endforeach;
            }
            ?>

        </td>
        <?php endfor;?>

        <td>
            <?php
            $totalThisHour = 0;
            foreach($totals[$hour] as $memberId => $memberVisits):
                $visit = reset($memberVisits);
                $totalThisHour+=count($memberVisits);

            ?>
            <div class="member" style="white-space: nowrap;">
                <span class="member-number"><?=$visit->Member->number?></span>
                <span class="member-name"><?=$visit->Member->getFullName()?></span> x
                <span class="member-visits-count"><?=count($memberVisits)?></span>
            </div>
            <?php endforeach;?>

        </td>

        <th valign="middle" align="center"><?=$totalThisHour;?></th>

    </tr>
<?php

$totalAllDays += $totalThisHour;
endforeach;?>
    <tr>
        <th>Total by day</th>
        <?php for($i=1;$i<=7;$i++):?>
        <th align="center" valign="middle"><?=$totalDays[$i]?></th>
        <?php endfor;?>
        <th colspan="2">Total all week: <?=$totalAllDays?></th>
    </tr>
    </tbody>
</table>