<?php
/** @var $member Members_Model_Mapper_Member */
foreach($this->list as $member):
    $activeSubscription = $member->getActiveSubscription();
    $lastVisit = $member->getLastVisit();
    ?>
<tr class="row" onclick="window.location.href = '<?php echo $this->url(array('module'=>'members','action'=>'view','id'=>$member->id), 'admin', true);?>' ">
    <td width="100"><?php echo $member->number;?></td>
    <td width="200"><?php echo $member->getFullName();?></td>
    <td><?php if($activeSubscription != false) echo $activeSubscription->Type->title;?></td>
    <td><?php if($activeSubscription != false) echo $activeSubscription->start_date.' -> '.$activeSubscription->expire_date;?></td>
    <td width="100">
    <?php
	if($activeSubscription != false && !empty($lastVisit) && empty($lastVisit->exit_time)):?>
        <?php echo $this->link('finish_visit', $this->url(array('module'=>'members','controller'=>'visit','action'=>'finish', 'member'=>$member->id), 'default', true), array('class'=>'button red-button'));?>
    <?php endif;?>
        </td>
</tr>
<?php endforeach;?>
<script type="text/javascript">
    moreResultsExists = <?php echo $this->moreResultsExists? 'true' : 'false';?>;
</script>