<?php $this->adminCurrentSubmenu(); ?>
<table class="admin-table-list">
	<tr>
		<th></th>
		<?php foreach($this->allRoles as $role) {?>
		<th><?php echo ucfirst($role->name); ?></th>
		<?php }?>
	</tr>
	<?php foreach($this->modules as $name=>$module) {?>
		<tr>
			<td width="10%"><?php echo ucfirst($name); ?></td>
			<?php foreach($this->allRoles as $role) {?>
			<td align="center"><?php echo $this->formCheckbox($name.$role->name, $this->acl->isAllowed(null, null, $name, array(), $role->name),array(),array('readonly'=>'readonly'), array('checkedValue'=>true)); ?></td>
			<?php }?>
		</tr>
	<?php }?>
</table>