Templater_Model_Mapper_Theme:
  connection: doctrine
  tableName: templater_themes
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    title:
      type: string(255)
    name:
      type: string(255)
    current:
      type: boolean
      default: false
    ordering:
      type: integer(11)
  relations:
    Layouts:
      class: Templater_Model_Mapper_Layout
      local: id
      foreign: theme_id
      type: many
      onDelete: CASCADE

Templater_Model_Mapper_Layout:
  connection: doctrine
  tableName: templater_layouts
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    title:
      type: string(255)
    name:
      type: string(255)
    theme_id:
      type: integer(11)
    params:
      type: array
    published:
      type: boolean
      default: false
  relations:
    Theme:
      class: Templater_Model_Mapper_Theme
      local: theme_id
      foreign: id
      type: one
      onDelete: CASCADE
    Widgets:
      class: Templater_Model_Mapper_Widget
      local: id
      foreign: layout_id
      type: many
    Points:
      class: Templater_Model_Mapper_LayoutPoint
      local: id
      foreign: layout_id
      type: many
      onDelete: CASCADE

Templater_Model_Mapper_LayoutPoint:
  connection: doctrine
  tableName: templater_layout_points
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    map_id:
      type: string(35)
    layout_id:
      type: integer(11)
  relations:
    Layout:
      class: Templater_Model_Mapper_Layout
      local: layout_id
      foreign: id
      type: one
      onDelete: CASCADE
      
Templater_Model_Mapper_Widget:
  connection: doctrine
  tableName: templater_widgets
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name:
      type: string(255)
    map_id:
      type: string(255)
    published:
      type: boolean
    layout_id:
      type: integer(11)
    ordering:
      type: integer(11)
    placeholder:
      type: string(255)
  relations:
    Layout:
      class: Templater_Model_Mapper_Layout
      local: layout_id
      foreign: id
      type: one
    WidgetPoints:
      class: Templater_Model_Mapper_WidgetPoint
      local: id
      foreign: widget_id
      type: many
      onDelete: CASCADE

Templater_Model_Mapper_WidgetPoint:
  connection: doctrine
  tableName: templater_widget_points
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    map_id:
      type: string(35)
    widget_id:
      type: integer(11)
  relations:
    Widget:
      class: Templater_Model_Mapper_Widget
      local: widget_id
      foreign: id
      type: one
      onDelete: CASCADE