<?php
$identity = Zend_Auth::getInstance()->getIdentity();
?>
<style type="text/css">

    .buy-product-button {
        width: 120px;
        height: 120px;
        float: left;
        margin: 0 10px 10px 0;
        padding: 4px;
        display: block;
        border: 1px solid silver;
        text-align: center;
        position: relative;
    }

    .buy-product-button a {
        position: absolute;
        bottom: 5px;
        left: 5px;
    }

    .buy-product-button h4 {

    }
    .buy-product-button p {
        font-size: 30px;
    }

    .buy-product-button p.stock, .buy-product-button p.sold {
        font-size: 14px;
    }

    .seven-days-sales div {
        font-size: 16px;
        border-bottom: 1px solid #dfdfdf;
        margin: 0 0 8px 0;
        padding: 0 0 2px 0;

    }
</style>
<table width="100%">
    <tr>
        <td valign="top">
            <h1><?php echo $this->translate('Products');?></h1>
            <?php
            /** @var $product Products_Model_Mapper_Product */
            foreach($this->list as $i => $product): ?>
            <div class="buy-product-button">
                <h3><?=$product->title?></h3>
                <p><?=$product->price?></p>
                <p class="stock">Stock: <?=$product->amount?></p>
                <?
                if($product->amount > 0) {
                    echo $this->link('BUY', $this->url(array('module'=>'products','action'=>'buy','id'=>$product->id),'admin',true), array('class'=>'button'));

                }
                else {
                    echo "<input type='button' value='".$this->translate('BUY')."' class='button light-grey-button'>";
                }
                ?>
                <div style="clear: both;"></div>
            </div>
            <?php endforeach;?>
        </td>
        <td width="15">&nbsp;</td>

        <td valign="top" width="300" class="seven-days-sales">
            <?php
            $totalToday = $totalWeek = 0;
            ?>

            <h1>Today products sales</h1>
            <?php
            $sales = Products_Model_DbTable_Product::getInstance()->getTodaySales();
            foreach($sales as $sale):
                $totalToday += $sale->total;
                ?>
                <div>
                    <?=$sale->title?>: <?=$sale->count?> (<?=$sale->total?>)
                </div>
            <? endforeach;?>

            <? if($identity->isAdmin()): ?>
            <br />
            <h1>7 Day's products sales</h1>
            <?php
            $sales = Products_Model_DbTable_Product::getInstance()->getSevenDaysSales();
            foreach($sales as $sale):
                $totalWeek += $sale->total;
                ?>
                <div>
                    <?=$sale->title?>: <?=$sale->count?> (<?=$sale->total?>)
                </div>
            <? endforeach;?>
            <? endif; ?>
            <br />
            <br />
            <h1>Today subscriptions sales</h1>
            <?php
            $sales = Members_Model_DbTable_SubscriptionType::getInstance()->getTodaySales();
            foreach($sales as $subscrType):
                $totalToday += $subscrType->total;
                ?>
                <div>
                    <div><a href="<?=$this->url(array('module'=>'members','controller' => 'report' ,'action'=>'subscriptions-sales','start'=> date('Y-m-d'), 'end' => date('Y-m-d'),'type' => $subscrType->id),'default',true)?>" class="modal-dialog-link dialog-size-s"><?=$subscrType->title?>: <?=$subscrType->count?> (<?=$subscrType->total?>)</a></div>
                </div>
            <? endforeach;?>

            <? if($identity->isAdmin()): ?>
            <br />
            <h1>7 Day's subscriptions sales</h1>
            <?php
            $sales = Members_Model_DbTable_SubscriptionType::getInstance()->getSevenDaysSales();

            foreach($sales as $subscrType):
                $totalWeek += $subscrType->total;
                ?>
                <div>
                    <a href="<?=$this->url(array('module'=>'members','controller' => 'report' ,'action'=>'subscriptions-sales','start'=> date('Y-m-d', strtotime('- 7 day')), 'end' => date('Y-m-d'),'type' => $subscrType->id),'default',true)?>" class="modal-dialog-link dialog-size-s"><?=$subscrType->title?>: <?=$subscrType->count?> (<?=$subscrType->total?>)</a>

                </div>
                <? endforeach;?>
            <? endif; ?>


            <? if($identity->isAdmin()): ?>
            <br />
            <br />
            <h1>Totals</h1>
            <div>Today sales income: <?=$totalToday?></div>
            <div>7 Days sales income: <?=$totalWeek?></div>
            <? endif; ?>

        </td>
    </tr>
</table>