<h1><?php echo $this->translate('Products');?></h1>
<?php echo $this->link('create_new_product', $this->url(array('module'=>'products','action'=>'edit'),'admin',true), array('class'=>'button plus-icon'));?>

<br />
<br />
<table class="admin-table-list">
    <?php
    /** @var $product Products_Model_Mapper_Product */
    foreach($this->list as $product):
        $editURL = $this->url(array('module'=>'products', 'action'=>'edit','id'=>$product->id), 'admin', true);
        ?>
        <tr class="row">
            <td width="160" onclick="window.location.href = '<?=$editURL?>' ">Price: <?php echo $product->price?></td>
            <td width="160" onclick="window.location.href = '<?=$editURL?>' ">In stock: <?php echo $product->amount?></td>
            <td onclick="window.location.href = '<?=$editURL?>' "><?php echo $product->title?></td>
        </tr>
        <?php endforeach;?>
</table>